- name: Send Discord message
        env:
          MESSAGE: "Don't forget to grab this week's redeem code: https://x.com/service"
        run: |
          jq -n --arg content "$MESSAGE" '{content: $content}' \
          | curl -H "Content-Type: application/json" -d @- ${{ secrets.DISCORD_WEBHOOK_URL }}
